In [5]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris

# Load the iris dataset
iris = load_iris()
X = iris.data

# Set the number of clusters
k = 3



# Initialize the centroids
centroids = [0, 0, 0, 0]

# Iterate until convergence
for i in range(5):
    # Fit the model to the data
    kmeans.fit(X)

    # Get the centroids for the current iteration
    new_centroids = kmeans.cluster_centers_

    # Print the centroids for the current iteration
    print("Iteration", i+1, "centroids:", new_centroids)

    # Check for convergence
    if np.allclose(new_centroids, centroids):
        print("Converged!")
        break

    # Update the centroids for the next iteration
    centroids = new_centroids

Iteration 1 centroids: [[5.006      3.428      1.462      0.246     ]
 [6.85       3.07368421 5.74210526 2.07105263]
 [5.9016129  2.7483871  4.39354839 1.43387097]]
Iteration 2 centroids: [[5.006      3.428      1.462      0.246     ]
 [6.85       3.07368421 5.74210526 2.07105263]
 [5.9016129  2.7483871  4.39354839 1.43387097]]
Converged!


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [6]:
import numpy as np
from sklearn.cluster import MiniBatchKMeans
from sklearn.datasets import load_iris

# Load the iris dataset
iris = load_iris()

# Set the number of clusters
k = 3

# Initialize the K-Means model
kmeans = MiniBatchKMeans(n_clusters=k, random_state=0, batch_size=10)

# Iterate over the data in chunks
for i in range(0, iris.data.shape[0], 10):
    X_batch = iris.data[i:i+10]

    # Fit the model to the current batch
    kmeans.partial_fit(X_batch)

# Print the centroids
print("Centroids:", kmeans.cluster_centers_)


Centroids: [[6.16548673 3.01681416 4.45752212 1.49026549]
 [4.4        2.88       1.28       0.2       ]
 [4.93125    3.228125   1.675      0.328125  ]]


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
